### ISSUE TITLE
Add character from clipboard doesn't work; Cannot remove scale imported from Anemnesis

### ISSUE THREAD

**Issue by WorstPirateYouEverSeen** [XIV-Tools/CustomizePlus#105]
After latest update I'm now having these 2 issues.

The "Add Character from clipboard" button just does absolutely nothing. I tried copying every preset I have saved and when I press the button nothing happens.

If I add empty scale and then import .scale file from Anemnesis I can no longer rename, save or delete that preset unless I quit the game and manually remove it from config file.

**Comment by StoiaCode** [comment]
For the Copy, itll just not create them if you have a scale with that exact name character. Try it with someone elses, or rename a scale before pasting.

Ill check that Ana issue soon.

**Comment by StoiaCode** [comment]
Please upload a copy of your json configuration file (default location is %APPDATA%\XIVLauncher\pluginConfigs\CustomizePlus.json)

**Comment by velemi** [comment]
I'm not having the issue with "Add character from clipboard", but I am having the issue where scales imported from Anamnesis can't be renamed or deleted. I am uploading my json config (uploaded with '.txt' extension because apparently github doesn't like json files).

[CustomizePlus.json.txt](https://github.com/XIV-Tools/CustomizePlus/files/11671647/CustomizePlus.json.txt)

This is a completely new customize+ install, where the only steps I have taken are:

1. Delete all existing configuration files and fully reinstall Customize+

2. Import a simple scaling file from anamnesis (in this case the scaling is named "Roe"). This scaling file becomes impossible to delete or re-name.

3. Export the "Roe" scaling file to the clipboard, and then import the scaling from clipboard for a new character.

4. There are now 2 scaling files named "Roe". The second one can be renamed, so I rename it to "Roe_clipboard_import". Note: while editing the name, it looks like it is editing the name for BOTH scalings, but only the second one actually gets renamed.

After this point, the 'Roe_clipboard_import' scaling works like any scaling file created entirely in Customize+, and can be renamed, deleted, etc, without any issues. However, the "Roe" scaling that was imported from anamnesis maintains the issues (can't rename, can't delete). As can be seen in the json file, they are exactly identical in the config.


The anamnesis-imported scales continue to function incorrectly like this until Customize+ is disabled and then re-enabled in the Dalamud plugins installer (or the game is restarted). Once the plugin has been reloaded like this, all scales seem to begin functioning as they should, regardless of how they were imported.

**Comment by StoiaCode** [comment]
Closing in favor of #122
