### ISSUE TITLE
Custmoize+ Failing with specific player

### ISSUE THREAD

**Issue by masamunewg** [XIV-Tools/CustomizePlus#115]
I can toggle Customize+ on/off without issue for all players (Mare synced, unsynced) even random players in town i can add their name and load a body scale, then enter gpose, and toggle it off and on rapidly and see it update real time.

But for 1 specific player character (My partner's...) even if we pause Mare sync, once i open gpose i cannot toggle on/off customize+ edits for that character. I have tried uninstalling customize+, closing the game and relaunching, deleting it from the plugins list on xiv launcher, and everything else I can think of.

I noticed when i reinstall Customize+ it has remembered my settings....How can i -truly- uninstall this plugin at it's core? I think this could help fix my issues.

Please at least tell me how to -fully- uninstall the plugin and all of its settings etc, so I can try to fix or reset this issue at least.
Thank you.

**Comment by StoiaCode** [comment]
In order to reset your settings (what you mean with uninstall) you need to go to %appdata%/XIVLauncher/ then inside there you can search for 'Customize' and delete everything that turns up (after deleting the plugin in game). 

And while you are at it try to DISABLE mare (go into the Plugin installer and entirely turn it off) next time you try. Sometimes scales linger longer then they should.

**Comment by masamunewg** [comment]
Deleting the appdata settings, amongst other resetting of various things, have resolved the issue! It doesnt seem to be a frequent issue and the .pose files are saved elsewhere, so its easy to recover from if it happens again! Thanks for the help!
