### ISSUE TITLE
Editor's automatic bone data retriever issues

### ISSUE THREAD

**Issue by AlexCSDev** [XIV-Tools/CustomizePlus#118]
While making some scales for NPCs I found the following issues with the current implementation of the automatic bone data retriever in the editor:

- It almost always fails for non-player characters, even if the character is next to you (aka loaded and should have bone data within ffxiv memory)
- When it fails to load bone data it deletes all bones with values which are not edited. So if I have non-edited clothing bones in my scale for the future use it just deletes all of them. I think the proper way of handling this will be to never overwrite bone list in scale unless user explicitly allows/asks for it.

**Comment by StoiaCode** [comment]
_You know what, fuck you *deletes your bones*_

Jokes aside, thats obviously unintended behaviour, but I think that at least the later part would be fixed with dendroids PR? That has an option to "show live bones" tho I must admit I did not yet check with NPCs. 

The failing to detect NPC bones at all is funny tho, did no one ever notice that? Lmao. But it does work if you import ana poses I suppose?

**Comment by AlexCSDev** [comment]
> Jokes aside, thats obviously unintended behaviour, but I think that at least the later part would be fixed with dendroids PR? That has an option to "show live bones" tho I must admit I did not yet check with NPCs.

Hard to say right now since, as I mentioned in PR, it's absolutely broken for me when it comes to NPCs.

> The failing to detect NPC bones at all is funny tho, did no one ever notice that? Lmao. But it does work if you import ana poses I suppose?

It should, but the issue is that, if I remember correctly, every time you open editor window it resets the bones to default ones because it can't find the character data in memory.

**Comment by dendr01d** [comment]
> It almost always fails for non-player characters, even if the character is next to you (aka loaded and should have bone data within ffxiv memory)

Can you expand on the specific issue you're having? I'm realizing now that the "Default" profile feature isn't working as intended (?) but inasmuch as detection and editing of npc bones goes, things seem to be working like they ought.

![image](https://github.com/XIV-Tools/CustomizePlus/assets/10487419/7c4c3178-4e96-4b6f-95e5-aaccb0d9da13)

![image](https://github.com/XIV-Tools/CustomizePlus/assets/10487419/4072286f-7fe9-4b1d-aec0-a5789030266c)

> When it fails to load bone data it deletes all bones with values which are not edited. So if I have non-edited clothing bones in my scale for the future use it just deletes all of them. I think the proper way of handling this will be to never overwrite bone list in scale unless user explicitly allows/asks for it.

This comes down to the UX I had in mind. Since I imagine it would rarely be the case that someone would spend much time editing a skeleton that they can't see, I figured it was better to display the minimal set of applicable information.

There's a practical reason for it, too. Let's say I write down the names of several players, NPCs, monsters, pets, and some random prop objects, then pick one of them at random. While alone in an inn room, I make a blank profile for the chosen name, and open the editor. Without any context, what bone information should it display?

**Comment by StoiaCode** [comment]
> There's a practical reason for it, too. Let's say I write down the names of several players, NPCs, monsters, pets, and some random prop objects, then pick one of them at random. While alone in an inn room, I make a blank profile for the chosen name, and open the editor. Without any context, what bone information should it display?

This would be one thing, but what Alex descriebs is you create a scale for someone thats there. Then they leave, then you open the editor. At that point it will go in and DELETE already existing bones that are unedited. It should never DELETE bones that have already been created once.

**Comment by dendr01d** [comment]
Ah, that's already fixed in the current PR branch then -- while open, the bone editor window only refreshes the displayed list when manually directed to.

**Comment by AlexCSDev** [comment]
> Can you expand on the specific issue you're having? I'm realizing now that the "Default" profile feature isn't working as intended (?) but inasmuch as detection and editing of npc bones goes, things seem to be working like they ought.

* Retainers: Create profile with retainer's name. When retainer appears the following error appears in log:
```ERR [CustomizePlus] Error obtaining skeleton from GameObject '4002250D(XXXXXXXX - Retainer) at 1F55F604010'```
* NPCs: Create profile for with name *Y'shtola. Start NG+ for Endwalker Part 1 and go through "The Next Ship to Sail" quest until you need to go to Limsa Lominsa. Go there and you will see the following error when approaching Ferry Docks area:
```ERR [CustomizePlus] Error obtaining skeleton from GameObject 'E0000000(Y'shtola - EventNpc) at 1F567EFE120'```

**Comment by dendr01d** [comment]
I took those screenshots using the live build

**Comment by AlexCSDev** [comment]
Hm... did a few quick tests, can't reproduce it right now either. Since it was tested in earlier version of the game I assume something might have changed since then? I'll close this for now and reopen it if I encounter this behavior again.
