### ISSUE TITLE
The global scale doesn't work anymore, after the last update.

### ISSUE THREAD

**Issue by 0Xymoar** [XIV-Tools/CustomizePlus#145]
Hello, 

Thanks for all your work !

Got an issue : I made my character with a global scale of 0.926 to make him shorter than the game can do, but it doesn't work anymore after the last update. 
All the other bones work, but the global scale doesn't. 

I tried to look into the other options, is that the root bone now ? If it is, it doesn't apply neither.

**Comment by AlexCSDev** [comment]
If you are running testing version, the root settings are broken there currently. Additionally we highly recommend using racial scaling instead of this option if you need to adjust the height of your character. Details about that can be found in pinned messages in c+ discord channel.

**Comment by StoiaCode** [comment]
Yeah sounds like testing.
Additionaly it was never called "global" scale. It always has been root bone. 
This is considered advanced now and will not be supported once it works again, due to our recommendation to instead use Racial Scaling in Penumbra, which works much more reliable. Ill refer you to #84
