### ISSUE TITLE
Shoulder distortion with no bone changes

### ISSUE THREAD

**Issue by gucciBane** [XIV-Tools/CustomizePlus#26]
I'm finding my shoulders get really warped even if the bones are all set to 1.0. This is me toggling an unchanged shape from 'disabled' to 'enabled.

https://user-images.githubusercontent.com/49180180/186836661-454256ce-19c7-40b8-84bc-48792792d050.mp4

'

**Comment by Phenrei** [comment]
What race and body type are you using? Can't tell for sure from the back. Also, is this during a gpose with an Anamnesis enabled? I'm not sure what in-game pose that would be otherwise. The two currently fight each other a little bit if scaling adjustment is on in Ana due to global vs local scaling. The pose may have some information due to a muscle slider or something else that is affecting it.

Also, if it's not gpose, try adding the character name fresh to start with a completely defaulted scale file loaded within the plugin and see if it still occurs. It may be affected by some other data if it was ever an import.

**Comment by gucciBane** [comment]
Thanks for the quick reply!

- Roegadyn male, HR3
- No Anamnesis
- the emote is /wasshoi (vanilla)

So, I deleted my own entry, made a new one, which had 'Default' on it, and Enabling it did that to my shoulders. Disabling fixed it. It appears this way both inside gpose and outside. It's weird, because just standing there in an idle, you see no difference.

**Comment by Phenrei** [comment]
It's likely then that the animation itself is scaling the bones to avoid clipping or deforming, and because C+ hooks straight into the render, it will override that. I'll look into it further after the UI pass, once I start digging into the pose/bone manipulations, as this sort of weirdness can come up during animations in cutscenes as well. WoL will be standing default and look normal and then some animation overrides some values and things go a little wonky, here and there. Larger body sizes make these all the weirder, I've run into similar with my Femroe, but I had a pretty significant modification on and didn't run into it without.

**Comment by gucciBane** [comment]
Very interesting. It makes sense. Not a huge deal since it rarely comes up, but nice to know I didn't mess something up. 

Thanks for the time and work on the project!

**Comment by StoiaCode** [comment]
This _should_ be fixed? Please let us know if you can still reproduce it.
