### ISSUE TITLE
[Feature] Support for exporting scales

### ISSUE THREAD

**Issue by Otaku-2** [XIV-Tools/CustomizePlus#28]
Even if it's just a "Copy scale to clipboard" that would then be required to be pasted into a .txt, then rename file extension to .scale, that would be useful.

**Comment by nullplz** [comment]
Currently the only way to share scalers is by getting the data out of the CustomizePlus.json file in %appdata%\XIVLauncher\pluginConfigs and manually transcribing it into an Anamnesis .pose file format, because the data format is different between the two.

Even some way to just accept data in the CustomizePlus.json format that doesn't require directly editing the .json would be better.
