### ISSUE TITLE
Customize+ Scaling Not Showing Up in Gpose

### ISSUE THREAD

**Issue by Aqualander** [XIV-Tools/CustomizePlus#43]
Hi there! I've been having an issue with Customize+ lately where as I'm playing the game normally, I can see my friend's body scalings just fine through Mare compability. But then when I try to enter Gpose, their scalings don't stay. They can see my scalings in Gpose, but I can't see theirs. Other friends are able to see their scalings in Gpose as well as mine. And I've tested with multiple friends, and I've had mixed results:

1) Friend scaled several bones on anam, uploaded to C+, shows normal in game, doesn't show in Gpose
2) Friend scaled neck directly in C+, shows normal in game, doesn't show in Gpose
3) Friend scaled root height directly in C+, shows normal in game, shows up in Gpose
4) Friend scaled several bones on anam and has a custom tail mod to their highlander, uploaded to C+, shows normal in game, body scaling shows up in Gpose, tail scaling does not show up in Gpose

I see all these scalings just fine through Mare while playing normally, so this bug seems to only happen during Gpose. There's so many factors that could affect this, and I'm not very familiar with the technology, but I'll provide whatever details I can to get this worked out.

**Comment by StoneColb** [comment]
Having an identical issue with a friend. It can't be me, because they have the exact same issue as well. A friend who uses it, however, said we appear in gpose just fine.

I have replicated all steps as well as uninstalled C+, disconnected from Mare, anything I can think of that's related.

Would love some help on this, as it seems to only be affecting myself and my other friend, but none of my friends besides

**Comment by StoneColb** [comment]
I found the solution... and feel rather dumb having done so.

Make sure "Apply to NPCs in cutscenes" is checked off. Di that, friends now load into gpose with their presets active.

**Comment by StoiaCode** [comment]
#84
