### ISSUE TITLE
[Feature Request] Position of bones?

### ISSUE THREAD

**Issue by seirralanzce** [XIV-Tools/CustomizePlus#57]
I wonder if it possible to adjust position like how we can do so in Ktisis/Anam position of bones and to be persist in Custmoize+

**Comment by StoiaCode** [comment]
No. Not possible sadly.

**Comment by Maguillage** [comment]
![image](https://user-images.githubusercontent.com/91387479/217620532-9846a13c-de75-42f8-b8c6-263b9931ce08.png)
Would be nice to have some sort of relative-to-waist/leg/etc position changes for the hip/cloth bones.
I use an extreme example here, but the poofy bits on outfits don't like it when you scale the waist too far since they won't follow the new scaling.
In anamnesis I can just shift bones over manually to get a good pic, but with an all-the-time scaling it can look a bit iffy.

**Comment by Allora02** [comment]
Any kind of position scaling/movement is impossible for customize+ as positioning changes will automatically break all animations. There is no way to implement this.
